<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin_client_chat extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Admin_client_chat_model');
    } 

    /*
     * Listing of admin_client_chat
     */
    function index()
    {
        $data['admin_client_chat'] = $this->Admin_client_chat_model->get_all_admin_client_chat();
        
        $data['_view'] = 'admin_client_chat/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new admin_client_chat
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'is_active' => $this->input->post('is_active'),
				'project_id' => $this->input->post('project_id'),
				'interaction_on' => $this->input->post('interaction_on'),
				'interaction_type' => $this->input->post('interaction_type'),
				'comment' => $this->input->post('comment'),
				'interaction_from' => $this->input->post('interaction_from'),
				'interaction_text' => $this->input->post('interaction_text'),
            );
            
            $admin_client_chat_id = $this->Admin_client_chat_model->add_admin_client_chat($params);
            redirect('admin_client_chat/index');
        }
        else
        {            
            $data['_view'] = 'admin_client_chat/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a admin_client_chat
     */
    function edit($interaction_id)
    {   
        // check if the admin_client_chat exists before trying to edit it
        $data['admin_client_chat'] = $this->Admin_client_chat_model->get_admin_client_chat($interaction_id);
        
        if(isset($data['admin_client_chat']['interaction_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'is_active' => $this->input->post('is_active'),
					'project_id' => $this->input->post('project_id'),
					'interaction_on' => $this->input->post('interaction_on'),
					'interaction_type' => $this->input->post('interaction_type'),
					'comment' => $this->input->post('comment'),
					'interaction_from' => $this->input->post('interaction_from'),
					'interaction_text' => $this->input->post('interaction_text'),
                );

                $this->Admin_client_chat_model->update_admin_client_chat($interaction_id,$params);            
                redirect('admin_client_chat/index');
            }
            else
            {
                $data['_view'] = 'admin_client_chat/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The admin_client_chat you are trying to edit does not exist.');
    } 

    /*
     * Deleting admin_client_chat
     */
    function remove($interaction_id)
    {
        $admin_client_chat = $this->Admin_client_chat_model->get_admin_client_chat($interaction_id);

        // check if the admin_client_chat exists before trying to delete it
        if(isset($admin_client_chat['interaction_id']))
        {
            $this->Admin_client_chat_model->delete_admin_client_chat($interaction_id);
            redirect('admin_client_chat/index');
        }
        else
            show_error('The admin_client_chat you are trying to delete does not exist.');
    }
    
}
