<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Client_detail extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $is_logged_in = $this->session->userdata("admin_id");
        if($is_logged_in == "" || $is_logged_in == null){
            redirect("dashboard/login");
        }
        $this->load->model('Client_detail_model');
    } 

    /*
     * Listing of client_details
     */
    function index($id="")
    {
        $data['client_details'] = $this->Client_detail_model->get_all_client_details($id);
        
        $data['_view'] = 'client_detail/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new client_detail
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required|alpha');
		$this->form_validation->set_rules('mobile_number','Mobile Number','required|exact_length[10]');
		$this->form_validation->set_rules('email_id','Email Id','required|valid_email');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'is_active' => $this->input->post('is_active'),
				'reach_in_whatsapp' => $this->input->post('reach_in_whatsapp'),
				'password' => $this->input->post('password'),
				'otp_validation' => $this->input->post('otp_validation'),
				'client_status' => $this->input->post('client_status'),
				'created_on' => $this->input->post('created_on'),
				'updated_on' => $this->input->post('updated_on'),
				'name' => $this->input->post('name'),
				'mobile_number' => $this->input->post('mobile_number'),
				'email_id' => $this->input->post('email_id'),
				'city' => $this->input->post('city'),
				'signup_on' => $this->input->post('signup_on'),
				'otp' => $this->input->post('otp'),
				'comments' => $this->input->post('comments'),
            );
            
            $client_detail_id = $this->Client_detail_model->add_client_detail($params);
            redirect('client_detail/index');
        }
        else
        {            
            $data['_view'] = 'client_detail/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a client_detail
     */
    function edit($client_id)
    {   
        // check if the client_detail exists before trying to edit it
        $data['client_detail'] = $this->Client_detail_model->get_client_detail($client_id);
        
        if(isset($data['client_detail']['client_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required|max_length[32]');
			$this->form_validation->set_rules('mobile_number','Mobile Number','required|exact_length[10]');
            $this->form_validation->set_rules('email_id','Email','valid_email');
			if($this->form_validation->run())     
            {   
                $params = array(
					'is_active' => $this->input->post('is_active'),
					'reach_in_whatsapp' => $this->input->post('reach_in_whatsapp'),
					'password' => $this->input->post('password'),
					'otp_validation' => $this->input->post('otp_validation'),
					'client_status' => $this->input->post('client_status'),
					'updated_on' => $this->input->post('updated_on'),
					'name' => $this->input->post('name'),
					'mobile_number' => $this->input->post('mobile_number'),
					'email_id' => $this->input->post('email_id'),
					'city' => $this->input->post('city'),
					'otp' => $this->input->post('otp'),
					'comments' => $this->input->post('comments'),
                );
                $this->session->set_flashdata('success','Client details updated successfully'); 
                $this->Client_detail_model->update_client_detail($client_id,$params);            
                redirect('client_detail/index');
            }
            else
            {
                $data['_view'] = 'client_detail/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The client_detail you are trying to edit does not exist.');
    } 

    /*
     * Deleting client_detail
     */
    function remove($client_id)
    {
        $client_detail = $this->Client_detail_model->get_client_detail($client_id);

        // check if the client_detail exists before trying to delete it
        if(isset($client_detail['client_id']))
        {
            $this->Client_detail_model->delete_client_detail($client_id);
            redirect('client_detail/index');
        }
        else
            show_error('The client_detail you are trying to delete does not exist.');
    }
    
}
