<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Client_escallation extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $is_logged_in = $this->session->userdata("admin_id");
        if($is_logged_in == "" || $is_logged_in == null){
            redirect("dashboard/login");
        }
        $this->load->model('Client_escallation_model');
    } 

    /*
     * Listing of client_escallation
     */
    function index()
    {
        $data['client_escallation'] = $this->Client_escallation_model->get_all_client_escallation();
        
        $data['_view'] = 'client_escallation/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new client_escallation
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'is_closed' => $this->input->post('is_closed'),
				'is_active' => $this->input->post('is_active'),
				'project_id' => $this->input->post('project_id'),
				'escallation_on' => $this->input->post('escallation_on'),
				'created_on' => $this->input->post('created_on'),
				'updated_on' => $this->input->post('updated_on'),
				'client_comments' => $this->input->post('client_comments'),
				'admin_comments' => $this->input->post('admin_comments'),
            );
            
            $client_escallation_id = $this->Client_escallation_model->add_client_escallation($params);
            redirect('client_escallation/index');
        }
        else
        {            
            $data['_view'] = 'client_escallation/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a client_escallation
     */
    function edit($escallation_id)
    {   
        // check if the client_escallation exists before trying to edit it
        $data['client_escallation'] = $this->Client_escallation_model->get_client_escallation($escallation_id);
        
        if(isset($data['client_escallation']['escallation_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'is_active' => $this->input->post('is_active'),
					'client_comments' => $this->input->post('client_comments'),
					'admin_comments' => $this->input->post('admin_comments'),
                    'updated_on' => date("Y-m-d H:i:s")
                );
                $this->session->set_flashdata('success','Client escallation updated successfully'); 
                $this->Client_escallation_model->update_client_escallation($escallation_id,$params);            
                redirect('client_escallation/index');
            }
            else
            {
                $data['_view'] = 'client_escallation/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The client_escallation you are trying to edit does not exist.');
    } 

    /*
     * Deleting client_escallation
     */
    function remove($escallation_id)
    {
        $client_escallation = $this->Client_escallation_model->get_client_escallation($escallation_id);

        // check if the client_escallation exists before trying to delete it
        if(isset($client_escallation['escallation_id']))
        {
            $this->Client_escallation_model->delete_client_escallation($escallation_id);
            redirect('client_escallation/index');
        }
        else
            show_error('The client_escallation you are trying to delete does not exist.');
    }
    
}
