<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        
    }

    function index()
    {
        $is_logged_in = $this->session->userdata("admin_id");
        if($is_logged_in == "" || $is_logged_in == null){
            redirect("dashboard/login");
        }else{
            $data['requested'] = $this->db->query("select * from project_menu where project_status='Quote Requested'")->num_rows();
            $data['completed'] = $this->db->query("select * from project_menu where project_status='Project Completed'")->num_rows();
            $data['design_accepted'] = $this->db->query("select * from project_menu where project_status='Design Accepted'")->num_rows();
            $data['first_payment'] = $this->db->query("select * from project_menu where project_status='Received First Payment'")->num_rows();
            $data['dropped'] = $this->db->query("select * from project_menu where project_status='Dropped'")->num_rows();
            $data['escallations'] = $this->db->query("select * from client_escallation where is_active='1'")->num_rows();
            $data['_view'] = 'dashboard';
            $this->load->view('layouts/main',$data);
        }
    }



	function login()
    {
        $is_logged_in = $this->session->userdata("admin_id");
        if($is_logged_in == "" || $is_logged_in == null){
            $this->load->view('login');
        }else{
            redirect('dashboard/index');
        }      
        
    }
	
	function logout(){
        $this->session->sess_destroy();
        redirect("dashboard/login");
    }
	
	function checkLogin(){
		
        if(isset($_POST) && count($_POST) > 0)     
        {
            $email = $_POST['email'];
            $password = $_POST['password'];
            $checkUser = $this->db->query("select * from admin_login where username='$email' AND password='$password'")->row_array();
            if(empty($checkUser)){
                $this->session->set_flashdata('err_msg', 'Please enter valid username and password');
                redirect('dashboard/login');
            }else{
				$this->session->set_userdata('admin_id',$checkUser['admin_id']);
				
				redirect("dashboard/index");
			
            }        
        }
        else
        {            
            //$data['_view'] = 'admin/login';
            $this->load->view('login');
        }
    }
}
