<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin_login_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get admin_login by admin_id
     */
    function get_admin_login($admin_id)
    {
        return $this->db->get_where('admin_login',array('admin_id'=>$admin_id))->row_array();
    }
        
    /*
     * Get all admin_login
     */
    function get_all_admin_login()
    {
        $this->db->order_by('admin_id', 'desc');
        return $this->db->get('admin_login')->result_array();
    }
        
    /*
     * function to add new admin_login
     */
    function add_admin_login($params)
    {
        $this->db->insert('admin_login',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update admin_login
     */
    function update_admin_login($admin_id,$params)
    {
        $this->db->where('admin_id',$admin_id);
        return $this->db->update('admin_login',$params);
    }
    
    /*
     * function to delete admin_login
     */
    function delete_admin_login($admin_id)
    {
        return $this->db->delete('admin_login',array('admin_id'=>$admin_id));
    }
}
