<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Marketing_partner_coupon_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get marketing_partner_coupon by coupon_id
     */
    function get_marketing_partner_coupon($coupon_id)
    {
        return $this->db->get_where('marketing_partner_coupons',array('coupon_id'=>$coupon_id))->row_array();
    }
        
    /*
     * Get all marketing_partner_coupons
     */
    function get_all_marketing_partner_coupons()
    {
        $this->db->order_by('coupon_id', 'desc');
        return $this->db->get('marketing_partner_coupons')->result_array();
    }
        
    /*
     * function to add new marketing_partner_coupon
     */
    function add_marketing_partner_coupon($params)
    {
        $this->db->insert('marketing_partner_coupons',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update marketing_partner_coupon
     */
    function update_marketing_partner_coupon($coupon_id,$params)
    {
        $this->db->where('coupon_id',$coupon_id);
        return $this->db->update('marketing_partner_coupons',$params);
    }
    
    /*
     * function to delete marketing_partner_coupon
     */
    function delete_marketing_partner_coupon($coupon_id)
    {
        return $this->db->delete('marketing_partner_coupons',array('coupon_id'=>$coupon_id));
    }
}
