<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Marketing_partner_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get marketing_partner by marketing_partner_id
     */
    function get_marketing_partner($marketing_partner_id)
    {
        return $this->db->get_where('marketing_partners',array('marketing_partner_id'=>$marketing_partner_id))->row_array();
    }
        
    /*
     * Get all marketing_partners
     */
    function get_all_marketing_partners()
    {
        $this->db->order_by('marketing_partner_id', 'desc');
        return $this->db->get('marketing_partners')->result_array();
    }
        
    /*
     * function to add new marketing_partner
     */
    function add_marketing_partner($params)
    {
        $this->db->insert('marketing_partners',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update marketing_partner
     */
    function update_marketing_partner($marketing_partner_id,$params)
    {
        $this->db->where('marketing_partner_id',$marketing_partner_id);
        return $this->db->update('marketing_partners',$params);
    }
    
    /*
     * function to delete marketing_partner
     */
    function delete_marketing_partner($marketing_partner_id)
    {
        return $this->db->delete('marketing_partners',array('marketing_partner_id'=>$marketing_partner_id));
    }
}
