<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Project_menu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get project_menu by project_id
     */
    function get_project_menu($project_id)
    {
        return $this->db->query("select *,DATE_FORMAT(first_paymnt_made_on,'%d-%m-%Y') as first_paymnt_made_on,DATE_FORMAT(second_paymnt_made_on,'%d-%m-%Y') as second_paymnt_made_on,DATE_FORMAT(completed_on,'%d-%m-%Y') as completed_on,DATE_FORMAT(project_start_date,'%d-%m-%Y') as project_start_date,DATE_FORMAT(promissed_handover_date,'%d-%m-%Y') as promissed_handover_date,DATE_FORMAT(actual_handover_date,'%d-%m-%Y') as actual_handover_date,DATE_FORMAT(po_date,'%d-%m-%Y') as po_date from project_menu where project_id=$project_id")->row_array();
    }
        
    /*
     * Get all project_menu
     */
    function get_all_project_menu($id,$v)
    {
        $this->db->order_by('project_id', 'desc');
        if($id!=""){
            if($v=='c'){
                $this->db->where('client_id', $id);
            }
            if($v=='p'){
                $this->db->where('project_id', $id);
            }
            if($v=='s'){
                $this->db->where('project_status', $id);
            }
            
        }
        return $this->db->get('project_menu')->result_array();
    }
        
    /*
     * function to add new project_menu
     */
    function add_project_menu($params)
    {
        $this->db->insert('project_menu',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update project_menu
     */
    function update_project_menu($project_id,$params)
    {
        $this->db->where('project_id',$project_id);
        return $this->db->update('project_menu',$params);
    }
    
    /*
     * function to delete project_menu
     */
    function delete_project_menu($project_id)
    {
        return $this->db->delete('project_menu',array('project_id'=>$project_id));
    }
}
